Need to discuss it, as the JSONs are too coupled.
Error: ### SQL: SELECT CONCAT(f.SID, m.suffix) AS col FROM feature f LEFT JOIN feature_mapping m ON f.type = m.type WHERE f.`type` = 'aEEG' AND (CASE WHEN false = TRUE THEN SID IN ('O2-Av17', 'T6-Av17', 'T4-Av17', 'F8-Av17', 'Fp2-Av17') ELSE electrode IN ('O2-Av17', 'T6-Av17', 'T4-Av17', 'F8-Av17', 'Fp2-Av17') END) AND (CASE WHEN m.comment IS NULL THEN range_low IN () ELSE m.comment IN () END)